version: 2

# Docker environment.
defaults: &defaults
  working_directory: /go/src/istio.io/istio
  docker:
    - image: gcr.io/istio-testing/circleci:2019-04-22
  environment:
    GOPATH: /go
    SKIP_CLEANUP: true

# org context settings. If developing on a clone, please configure:

# DOCKER_USER
# DOCKER_PASS
# HUB: ex istio, costinm (it is not the hub, but the dockerhub org or user)

# VM environment. Includes docker.
integrationDefaults: &integrationDefaults
  machine: true
  working_directory: /go/src/istio.io/istio #same as docker
  environment:
    - CHANGE_MINIKUBE_NONE_USER: true
    - GOPATH: /go
    - SKIP_CLEANUP: true
    - KUBECONFIG: /go/out/minikube.conf
    - TEST_ENV: minikube-none

# Common procedure to initialize working directory
initWorkingDir: &initWorkingDir
  type: shell
  name: Initialize Working Directory
  pwd: /
  command: |
    sudo mkdir -p /go/src/istio.io/istio
    sudo chown -R circleci /go
    mkdir -p /go/out/tests
    mkdir -p /go/out/logs
    mkdir -p /home/circleci/logs
    # TODO - temporary until 'machine' image is updated or customized
    GOROOT=$(go env GOROOT)
    sudo rm -r $(go env GOROOT)
    sudo mkdir $GOROOT
    curl https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1

recordZeroExitCodeIfTestPassed: &recordZeroExitCodeIfTestPassed
  run:
    when: on_success
    name: Record zero exit code as test passed
    command: echo 0 > exit_code

recordNonzeroExitCodeIfTestFailed: &recordNonzeroExitCodeIfTestFailed
  run:
    when: on_fail
    name: Record nonzero exit code as test failed
    command: echo 1 > exit_code

markJobStartsOnGCS: &markJobStartsOnGCS
  run:
    when: always
    command: bin/ci2gubernator.sh --job_starts

markJobFinishesOnGCS: &markJobFinishesOnGCS
  run:
    when: always
    command: |
      make junit-report || true
      # TODO: upload the artifacts as well, for debugging !
      bin/ci2gubernator.sh --exit_code=$(cat exit_code) --junit_xml=/go/out/tests/junit.xml
      make dumpsys || true

jobs:
  e2e-pilot-auth-v1alpha3-v2:
    <<: *integrationDefaults
    steps:
      - <<: *initWorkingDir
      - checkout
      - attach_workspace:
          at:  /go
      - <<: *markJobStartsOnGCS
      - run: make sync
      - run: bin/testEnvRootMinikube.sh start
      - run:
          command: |
            if [ ! -f /go/out/linux_amd64/release/pilot-discovery ]; then
              # Should only happen when re-running a job, and the workspace is gone
              time make build test-bins
            fi
            make docker.all generate_e2e_yaml
      - run: bin/testEnvRootMinikube.sh wait
      - run: docker images
      - run:
          no_output_timeout: 20m
          command: |
            make test/local/auth/e2e_pilotv2
      - <<: *recordZeroExitCodeIfTestPassed
      - <<: *recordNonzeroExitCodeIfTestFailed
      - <<: *markJobFinishesOnGCS
      - store_test_results:
          path: /go/out/tests
      - store_artifacts:
          path: /go/out/logs
      - store_artifacts:
          path: /tmp
  test:
    <<: *defaults
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    resource_class: xlarge
    steps:
      - checkout
      - <<: *markJobStartsOnGCS
      - run: make sync
      - run:
          command: |
            mkdir -p /go/out/tests
            export PATH=$GOPATH/bin:$PATH
            make localTestEnv
            set -o pipefail
            make test T=-v | tee -a /go/out/tests/build-log.txt
      - <<: *recordZeroExitCodeIfTestPassed
      - <<: *recordNonzeroExitCodeIfTestFailed
      - <<: *markJobFinishesOnGCS
      - store_test_results:
          path: /go/out/tests

  build:
    <<: *defaults
    resource_class: xlarge
    steps:
      - checkout
      - run: make sync
      - run: make build test-bins /go/bin/go-junit-report
      - persist_to_workspace:
          root: /go
          paths:
            - pkg/linux_amd64
            - bin
            - out
      - run:  make sidecar.deb
      - store_artifacts:
          path: /go/out/istio-sidecar.deb

workflows:
  version: 2
  # Ran nightly to check against prow tests
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - test
      - build
      - e2e-pilot-auth-v1alpha3-v2:
          requires:
            - test
            - build
