// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package ratelimit_config

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RateConfig_UnitType int32

const (
	RateConfig_UNKNOWN RateConfig_UnitType = 0
	RateConfig_SECOND  RateConfig_UnitType = 1
	RateConfig_MINUTE  RateConfig_UnitType = 2
	RateConfig_HOUR    RateConfig_UnitType = 3
	RateConfig_DAY     RateConfig_UnitType = 4
)

var RateConfig_UnitType_name = map[int32]string{
	0: "UNKNOWN",
	1: "SECOND",
	2: "MINUTE",
	3: "HOUR",
	4: "DAY",
}

var RateConfig_UnitType_value = map[string]int32{
	"UNKNOWN": 0,
	"SECOND":  1,
	"MINUTE":  2,
	"HOUR":    3,
	"DAY":     4,
}

func (x RateConfig_UnitType) String() string {
	return proto.EnumName(RateConfig_UnitType_name, int32(x))
}

func (RateConfig_UnitType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0, 0}
}

type RespCode_Code int32

const (
	RespCode_UNKNOWN                 RespCode_Code = 0
	RespCode_SUCCESS                 RespCode_Code = 1
	RespCode_FAILED                  RespCode_Code = 2
	RespCode_CONFIG_DOMAIN_EXSIST    RespCode_Code = 3
	RespCode_CONFIG_DOMAIN_NOT_FOUND RespCode_Code = 4
)

var RespCode_Code_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAILED",
	3: "CONFIG_DOMAIN_EXSIST",
	4: "CONFIG_DOMAIN_NOT_FOUND",
}

var RespCode_Code_value = map[string]int32{
	"UNKNOWN":                 0,
	"SUCCESS":                 1,
	"FAILED":                  2,
	"CONFIG_DOMAIN_EXSIST":    3,
	"CONFIG_DOMAIN_NOT_FOUND": 4,
}

func (x RespCode_Code) String() string {
	return proto.EnumName(RespCode_Code_name, int32(x))
}

func (RespCode_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3, 0}
}

type RateConfig struct {
	Unit                 RateConfig_UnitType `protobuf:"varint,1,opt,name=unit,proto3,enum=ratelimit.config.RateConfig_UnitType" json:"unit,omitempty"`
	RequestsPerUnit      uint32              `protobuf:"varint,2,opt,name=requests_per_unit,json=requestsPerUnit,proto3" json:"requests_per_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RateConfig) Reset()         { *m = RateConfig{} }
func (m *RateConfig) String() string { return proto.CompactTextString(m) }
func (*RateConfig) ProtoMessage()    {}
func (*RateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *RateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateConfig.Unmarshal(m, b)
}
func (m *RateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateConfig.Marshal(b, m, deterministic)
}
func (m *RateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateConfig.Merge(m, src)
}
func (m *RateConfig) XXX_Size() int {
	return xxx_messageInfo_RateConfig.Size(m)
}
func (m *RateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RateConfig proto.InternalMessageInfo

func (m *RateConfig) GetUnit() RateConfig_UnitType {
	if m != nil {
		return m.Unit
	}
	return RateConfig_UNKNOWN
}

func (m *RateConfig) GetRequestsPerUnit() uint32 {
	if m != nil {
		return m.RequestsPerUnit
	}
	return 0
}

type RateLimitDescriptorConfig struct {
	Key                  string                       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string                       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RateLimit            *RateConfig                  `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Descriptors          []*RateLimitDescriptorConfig `protobuf:"bytes,4,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RateLimitDescriptorConfig) Reset()         { *m = RateLimitDescriptorConfig{} }
func (m *RateLimitDescriptorConfig) String() string { return proto.CompactTextString(m) }
func (*RateLimitDescriptorConfig) ProtoMessage()    {}
func (*RateLimitDescriptorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *RateLimitDescriptorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimitDescriptorConfig.Unmarshal(m, b)
}
func (m *RateLimitDescriptorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimitDescriptorConfig.Marshal(b, m, deterministic)
}
func (m *RateLimitDescriptorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimitDescriptorConfig.Merge(m, src)
}
func (m *RateLimitDescriptorConfig) XXX_Size() int {
	return xxx_messageInfo_RateLimitDescriptorConfig.Size(m)
}
func (m *RateLimitDescriptorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimitDescriptorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimitDescriptorConfig proto.InternalMessageInfo

func (m *RateLimitDescriptorConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RateLimitDescriptorConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RateLimitDescriptorConfig) GetRateLimit() *RateConfig {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

func (m *RateLimitDescriptorConfig) GetDescriptors() []*RateLimitDescriptorConfig {
	if m != nil {
		return m.Descriptors
	}
	return nil
}

type RateLimitConf struct {
	Domain               string                       `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Descriptors          []*RateLimitDescriptorConfig `protobuf:"bytes,2,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RateLimitConf) Reset()         { *m = RateLimitConf{} }
func (m *RateLimitConf) String() string { return proto.CompactTextString(m) }
func (*RateLimitConf) ProtoMessage()    {}
func (*RateLimitConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *RateLimitConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimitConf.Unmarshal(m, b)
}
func (m *RateLimitConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimitConf.Marshal(b, m, deterministic)
}
func (m *RateLimitConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimitConf.Merge(m, src)
}
func (m *RateLimitConf) XXX_Size() int {
	return xxx_messageInfo_RateLimitConf.Size(m)
}
func (m *RateLimitConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimitConf.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimitConf proto.InternalMessageInfo

func (m *RateLimitConf) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RateLimitConf) GetDescriptors() []*RateLimitDescriptorConfig {
	if m != nil {
		return m.Descriptors
	}
	return nil
}

type RespCode struct {
	Domain               string        `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	RetCode              RespCode_Code `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3,enum=ratelimit.config.RespCode_Code" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RespCode) Reset()         { *m = RespCode{} }
func (m *RespCode) String() string { return proto.CompactTextString(m) }
func (*RespCode) ProtoMessage()    {}
func (*RespCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *RespCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCode.Unmarshal(m, b)
}
func (m *RespCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCode.Marshal(b, m, deterministic)
}
func (m *RespCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCode.Merge(m, src)
}
func (m *RespCode) XXX_Size() int {
	return xxx_messageInfo_RespCode.Size(m)
}
func (m *RespCode) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCode.DiscardUnknown(m)
}

var xxx_messageInfo_RespCode proto.InternalMessageInfo

func (m *RespCode) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RespCode) GetRetCode() RespCode_Code {
	if m != nil {
		return m.RetCode
	}
	return RespCode_UNKNOWN
}

type AddRatelimitConfigReq struct {
	Config               *RateLimitConf `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddRatelimitConfigReq) Reset()         { *m = AddRatelimitConfigReq{} }
func (m *AddRatelimitConfigReq) String() string { return proto.CompactTextString(m) }
func (*AddRatelimitConfigReq) ProtoMessage()    {}
func (*AddRatelimitConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *AddRatelimitConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRatelimitConfigReq.Unmarshal(m, b)
}
func (m *AddRatelimitConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRatelimitConfigReq.Marshal(b, m, deterministic)
}
func (m *AddRatelimitConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRatelimitConfigReq.Merge(m, src)
}
func (m *AddRatelimitConfigReq) XXX_Size() int {
	return xxx_messageInfo_AddRatelimitConfigReq.Size(m)
}
func (m *AddRatelimitConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRatelimitConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddRatelimitConfigReq proto.InternalMessageInfo

func (m *AddRatelimitConfigReq) GetConfig() *RateLimitConf {
	if m != nil {
		return m.Config
	}
	return nil
}

type AddRatelimitConfigResp struct {
	Ret                  *RespCode `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddRatelimitConfigResp) Reset()         { *m = AddRatelimitConfigResp{} }
func (m *AddRatelimitConfigResp) String() string { return proto.CompactTextString(m) }
func (*AddRatelimitConfigResp) ProtoMessage()    {}
func (*AddRatelimitConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}

func (m *AddRatelimitConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRatelimitConfigResp.Unmarshal(m, b)
}
func (m *AddRatelimitConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRatelimitConfigResp.Marshal(b, m, deterministic)
}
func (m *AddRatelimitConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRatelimitConfigResp.Merge(m, src)
}
func (m *AddRatelimitConfigResp) XXX_Size() int {
	return xxx_messageInfo_AddRatelimitConfigResp.Size(m)
}
func (m *AddRatelimitConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRatelimitConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddRatelimitConfigResp proto.InternalMessageInfo

func (m *AddRatelimitConfigResp) GetRet() *RespCode {
	if m != nil {
		return m.Ret
	}
	return nil
}

type GetRatelimitConfigReq struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatelimitConfigReq) Reset()         { *m = GetRatelimitConfigReq{} }
func (m *GetRatelimitConfigReq) String() string { return proto.CompactTextString(m) }
func (*GetRatelimitConfigReq) ProtoMessage()    {}
func (*GetRatelimitConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{6}
}

func (m *GetRatelimitConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatelimitConfigReq.Unmarshal(m, b)
}
func (m *GetRatelimitConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatelimitConfigReq.Marshal(b, m, deterministic)
}
func (m *GetRatelimitConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatelimitConfigReq.Merge(m, src)
}
func (m *GetRatelimitConfigReq) XXX_Size() int {
	return xxx_messageInfo_GetRatelimitConfigReq.Size(m)
}
func (m *GetRatelimitConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatelimitConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatelimitConfigReq proto.InternalMessageInfo

func (m *GetRatelimitConfigReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type GetRatelimitConfigResp struct {
	Config               *RateLimitConf `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRatelimitConfigResp) Reset()         { *m = GetRatelimitConfigResp{} }
func (m *GetRatelimitConfigResp) String() string { return proto.CompactTextString(m) }
func (*GetRatelimitConfigResp) ProtoMessage()    {}
func (*GetRatelimitConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{7}
}

func (m *GetRatelimitConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatelimitConfigResp.Unmarshal(m, b)
}
func (m *GetRatelimitConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatelimitConfigResp.Marshal(b, m, deterministic)
}
func (m *GetRatelimitConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatelimitConfigResp.Merge(m, src)
}
func (m *GetRatelimitConfigResp) XXX_Size() int {
	return xxx_messageInfo_GetRatelimitConfigResp.Size(m)
}
func (m *GetRatelimitConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatelimitConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatelimitConfigResp proto.InternalMessageInfo

func (m *GetRatelimitConfigResp) GetConfig() *RateLimitConf {
	if m != nil {
		return m.Config
	}
	return nil
}

type UpdateRatelimitConfigReq struct {
	Config               *RateLimitConf `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRatelimitConfigReq) Reset()         { *m = UpdateRatelimitConfigReq{} }
func (m *UpdateRatelimitConfigReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRatelimitConfigReq) ProtoMessage()    {}
func (*UpdateRatelimitConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{8}
}

func (m *UpdateRatelimitConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRatelimitConfigReq.Unmarshal(m, b)
}
func (m *UpdateRatelimitConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRatelimitConfigReq.Marshal(b, m, deterministic)
}
func (m *UpdateRatelimitConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRatelimitConfigReq.Merge(m, src)
}
func (m *UpdateRatelimitConfigReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRatelimitConfigReq.Size(m)
}
func (m *UpdateRatelimitConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRatelimitConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRatelimitConfigReq proto.InternalMessageInfo

func (m *UpdateRatelimitConfigReq) GetConfig() *RateLimitConf {
	if m != nil {
		return m.Config
	}
	return nil
}

type UpdateRatelimitConfigResp struct {
	Ret                  *RespCode `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateRatelimitConfigResp) Reset()         { *m = UpdateRatelimitConfigResp{} }
func (m *UpdateRatelimitConfigResp) String() string { return proto.CompactTextString(m) }
func (*UpdateRatelimitConfigResp) ProtoMessage()    {}
func (*UpdateRatelimitConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{9}
}

func (m *UpdateRatelimitConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRatelimitConfigResp.Unmarshal(m, b)
}
func (m *UpdateRatelimitConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRatelimitConfigResp.Marshal(b, m, deterministic)
}
func (m *UpdateRatelimitConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRatelimitConfigResp.Merge(m, src)
}
func (m *UpdateRatelimitConfigResp) XXX_Size() int {
	return xxx_messageInfo_UpdateRatelimitConfigResp.Size(m)
}
func (m *UpdateRatelimitConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRatelimitConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRatelimitConfigResp proto.InternalMessageInfo

func (m *UpdateRatelimitConfigResp) GetRet() *RespCode {
	if m != nil {
		return m.Ret
	}
	return nil
}

type DeleteRatelimitConfigReq struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRatelimitConfigReq) Reset()         { *m = DeleteRatelimitConfigReq{} }
func (m *DeleteRatelimitConfigReq) String() string { return proto.CompactTextString(m) }
func (*DeleteRatelimitConfigReq) ProtoMessage()    {}
func (*DeleteRatelimitConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{10}
}

func (m *DeleteRatelimitConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRatelimitConfigReq.Unmarshal(m, b)
}
func (m *DeleteRatelimitConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRatelimitConfigReq.Marshal(b, m, deterministic)
}
func (m *DeleteRatelimitConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRatelimitConfigReq.Merge(m, src)
}
func (m *DeleteRatelimitConfigReq) XXX_Size() int {
	return xxx_messageInfo_DeleteRatelimitConfigReq.Size(m)
}
func (m *DeleteRatelimitConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRatelimitConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRatelimitConfigReq proto.InternalMessageInfo

func (m *DeleteRatelimitConfigReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type DeleteRatelimitConfigResp struct {
	Ret                  *RespCode `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteRatelimitConfigResp) Reset()         { *m = DeleteRatelimitConfigResp{} }
func (m *DeleteRatelimitConfigResp) String() string { return proto.CompactTextString(m) }
func (*DeleteRatelimitConfigResp) ProtoMessage()    {}
func (*DeleteRatelimitConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{11}
}

func (m *DeleteRatelimitConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRatelimitConfigResp.Unmarshal(m, b)
}
func (m *DeleteRatelimitConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRatelimitConfigResp.Marshal(b, m, deterministic)
}
func (m *DeleteRatelimitConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRatelimitConfigResp.Merge(m, src)
}
func (m *DeleteRatelimitConfigResp) XXX_Size() int {
	return xxx_messageInfo_DeleteRatelimitConfigResp.Size(m)
}
func (m *DeleteRatelimitConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRatelimitConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRatelimitConfigResp proto.InternalMessageInfo

func (m *DeleteRatelimitConfigResp) GetRet() *RespCode {
	if m != nil {
		return m.Ret
	}
	return nil
}

type ListRatelimitConfigReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRatelimitConfigReq) Reset()         { *m = ListRatelimitConfigReq{} }
func (m *ListRatelimitConfigReq) String() string { return proto.CompactTextString(m) }
func (*ListRatelimitConfigReq) ProtoMessage()    {}
func (*ListRatelimitConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{12}
}

func (m *ListRatelimitConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatelimitConfigReq.Unmarshal(m, b)
}
func (m *ListRatelimitConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatelimitConfigReq.Marshal(b, m, deterministic)
}
func (m *ListRatelimitConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatelimitConfigReq.Merge(m, src)
}
func (m *ListRatelimitConfigReq) XXX_Size() int {
	return xxx_messageInfo_ListRatelimitConfigReq.Size(m)
}
func (m *ListRatelimitConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatelimitConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatelimitConfigReq proto.InternalMessageInfo

type ListRatelimitConfigRes struct {
	Configs              []*RateLimitConf `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListRatelimitConfigRes) Reset()         { *m = ListRatelimitConfigRes{} }
func (m *ListRatelimitConfigRes) String() string { return proto.CompactTextString(m) }
func (*ListRatelimitConfigRes) ProtoMessage()    {}
func (*ListRatelimitConfigRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{13}
}

func (m *ListRatelimitConfigRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatelimitConfigRes.Unmarshal(m, b)
}
func (m *ListRatelimitConfigRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatelimitConfigRes.Marshal(b, m, deterministic)
}
func (m *ListRatelimitConfigRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatelimitConfigRes.Merge(m, src)
}
func (m *ListRatelimitConfigRes) XXX_Size() int {
	return xxx_messageInfo_ListRatelimitConfigRes.Size(m)
}
func (m *ListRatelimitConfigRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatelimitConfigRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatelimitConfigRes proto.InternalMessageInfo

func (m *ListRatelimitConfigRes) GetConfigs() []*RateLimitConf {
	if m != nil {
		return m.Configs
	}
	return nil
}

func init() {
	proto.RegisterEnum("ratelimit.config.RateConfig_UnitType", RateConfig_UnitType_name, RateConfig_UnitType_value)
	proto.RegisterEnum("ratelimit.config.RespCode_Code", RespCode_Code_name, RespCode_Code_value)
	proto.RegisterType((*RateConfig)(nil), "ratelimit.config.RateConfig")
	proto.RegisterType((*RateLimitDescriptorConfig)(nil), "ratelimit.config.RateLimitDescriptorConfig")
	proto.RegisterType((*RateLimitConf)(nil), "ratelimit.config.RateLimitConf")
	proto.RegisterType((*RespCode)(nil), "ratelimit.config.RespCode")
	proto.RegisterType((*AddRatelimitConfigReq)(nil), "ratelimit.config.AddRatelimitConfigReq")
	proto.RegisterType((*AddRatelimitConfigResp)(nil), "ratelimit.config.AddRatelimitConfigResp")
	proto.RegisterType((*GetRatelimitConfigReq)(nil), "ratelimit.config.GetRatelimitConfigReq")
	proto.RegisterType((*GetRatelimitConfigResp)(nil), "ratelimit.config.GetRatelimitConfigResp")
	proto.RegisterType((*UpdateRatelimitConfigReq)(nil), "ratelimit.config.UpdateRatelimitConfigReq")
	proto.RegisterType((*UpdateRatelimitConfigResp)(nil), "ratelimit.config.UpdateRatelimitConfigResp")
	proto.RegisterType((*DeleteRatelimitConfigReq)(nil), "ratelimit.config.DeleteRatelimitConfigReq")
	proto.RegisterType((*DeleteRatelimitConfigResp)(nil), "ratelimit.config.DeleteRatelimitConfigResp")
	proto.RegisterType((*ListRatelimitConfigReq)(nil), "ratelimit.config.ListRatelimitConfigReq")
	proto.RegisterType((*ListRatelimitConfigRes)(nil), "ratelimit.config.ListRatelimitConfigRes")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0x68, 0xbb, 0x5b, 0x36, 0x82, 0xb5, 0x95, 0xac, 0x20, 0x51, 0x45, 0x42, 0x54,
	0x1b, 0x0a, 0x28, 0x3c, 0xa0, 0xc1, 0x53, 0x97, 0xb4, 0x23, 0x62, 0x4b, 0x86, 0xd3, 0x88, 0x8f,
	0x97, 0xa8, 0x34, 0x66, 0x8a, 0xe8, 0x9a, 0xcc, 0xf6, 0x26, 0xed, 0x97, 0xf1, 0xc2, 0x1b, 0x3f,
	0x80, 0xbf, 0x84, 0xf2, 0xd1, 0x7d, 0xd5, 0x81, 0x0d, 0x78, 0xa9, 0xec, 0xfa, 0xdc, 0x73, 0xee,
	0x3d, 0x3e, 0x91, 0xe1, 0xce, 0x24, 0x99, 0x7d, 0x89, 0x0f, 0x8c, 0x94, 0x26, 0x3c, 0x41, 0x2a,
	0x1d, 0x73, 0x32, 0x8d, 0x0f, 0x63, 0x6e, 0x14, 0xff, 0xeb, 0xdf, 0x24, 0x00, 0x3c, 0xe6, 0xc4,
	0xca, 0xb7, 0x68, 0x0b, 0x94, 0xe3, 0x59, 0xcc, 0x35, 0xa9, 0x2b, 0xf5, 0x56, 0xcc, 0xc7, 0xc6,
	0x55, 0xbc, 0x71, 0x8e, 0x35, 0x82, 0x59, 0xcc, 0x47, 0xa7, 0x29, 0xc1, 0x79, 0x09, 0xda, 0x80,
	0x7b, 0x94, 0x1c, 0x1d, 0x13, 0xc6, 0x59, 0x98, 0x12, 0x1a, 0xe6, 0x3c, 0xb5, 0xae, 0xd4, 0x5b,
	0xc6, 0x77, 0xe7, 0x07, 0xfb, 0x84, 0x66, 0x55, 0xfa, 0x36, 0x34, 0xe7, 0xd5, 0xa8, 0x05, 0x8d,
	0xc0, 0x7d, 0xeb, 0x7a, 0xef, 0x5d, 0xf5, 0x16, 0x02, 0xa8, 0xfb, 0x03, 0xcb, 0x73, 0x6d, 0x55,
	0xca, 0xd6, 0x7b, 0x8e, 0x1b, 0x8c, 0x06, 0x6a, 0x0d, 0x35, 0x41, 0x79, 0xe3, 0x05, 0x58, 0x95,
	0x51, 0x03, 0x64, 0xbb, 0xff, 0x51, 0x55, 0xf4, 0x9f, 0x12, 0xac, 0x67, 0xdd, 0xec, 0x66, 0xed,
	0xd9, 0x84, 0x4d, 0x68, 0x9c, 0xf2, 0x84, 0x96, 0x83, 0xa8, 0x20, 0x7f, 0x25, 0xa7, 0xf9, 0x1c,
	0x4b, 0x38, 0x5b, 0xa2, 0x55, 0xb8, 0x7d, 0x32, 0x9e, 0x1e, 0x93, 0xbc, 0xa7, 0x25, 0x5c, 0x6c,
	0xd0, 0x6b, 0x80, 0x6c, 0xc6, 0x30, 0x1f, 0x52, 0x93, 0xbb, 0x52, 0xaf, 0x65, 0x3e, 0xfc, 0xdd,
	0xd8, 0x78, 0x89, 0xce, 0x45, 0xd1, 0x1e, 0xb4, 0xa2, 0x33, 0x61, 0xa6, 0x29, 0x5d, 0xb9, 0xd7,
	0x32, 0x37, 0xc5, 0xd5, 0xc2, 0x36, 0xf1, 0xc5, 0x7a, 0xfd, 0x04, 0x96, 0xcf, 0x90, 0xd9, 0x39,
	0x6a, 0x43, 0x3d, 0x4a, 0x0e, 0xc7, 0xf1, 0xac, 0x9c, 0xa3, 0xdc, 0x5d, 0xd5, 0xad, 0xfd, 0xa3,
	0xee, 0x0f, 0x09, 0x9a, 0x98, 0xb0, 0xd4, 0x4a, 0x22, 0x52, 0xa9, 0xf9, 0x0a, 0x9a, 0x94, 0xf0,
	0x70, 0x92, 0x44, 0x85, 0x83, 0x2b, 0xe6, 0x23, 0x81, 0x60, 0xc9, 0x62, 0x64, 0x3f, 0xb8, 0x41,
	0x09, 0xcf, 0x16, 0xfa, 0x04, 0x94, 0x9c, 0xfb, 0xd2, 0x55, 0xb7, 0xa0, 0xe1, 0x07, 0x96, 0x35,
	0xf0, 0xfd, 0xe2, 0xae, 0x87, 0x7d, 0x67, 0x77, 0x60, 0xab, 0x35, 0xa4, 0xc1, 0xaa, 0xe5, 0xb9,
	0x43, 0x67, 0x27, 0xb4, 0xbd, 0xbd, 0xbe, 0xe3, 0x86, 0x83, 0x0f, 0xbe, 0xe3, 0x8f, 0x54, 0x19,
	0x3d, 0x80, 0xfb, 0x97, 0x4f, 0x5c, 0x6f, 0x14, 0x0e, 0xbd, 0xc0, 0xb5, 0x55, 0x45, 0xdf, 0x87,
	0xb5, 0x7e, 0x14, 0xe1, 0x79, 0x4b, 0xe5, 0xa0, 0xe4, 0x08, 0xbd, 0x84, 0x7a, 0xd1, 0x5e, 0x3e,
	0x51, 0x4b, 0xd8, 0xf7, 0x45, 0xdb, 0x71, 0x09, 0xd7, 0x87, 0xd0, 0x16, 0x31, 0xb2, 0x14, 0x3d,
	0x05, 0x99, 0x12, 0x5e, 0xf2, 0x75, 0xaa, 0x7d, 0xc0, 0x19, 0x4c, 0x7f, 0x06, 0x6b, 0x3b, 0x84,
	0x0b, 0x3a, 0xab, 0xf0, 0x5a, 0x7f, 0x07, 0x6d, 0x51, 0x01, 0x4b, 0xff, 0x7e, 0x16, 0x1f, 0xb4,
	0x20, 0x8d, 0xc6, 0x9c, 0xfc, 0x4f, 0x83, 0x1c, 0x58, 0xaf, 0x20, 0xbd, 0xb1, 0x47, 0x26, 0x68,
	0x36, 0x99, 0x12, 0x61, 0x7f, 0x55, 0x36, 0x39, 0xb0, 0x5e, 0x51, 0x73, 0x63, 0x79, 0x0d, 0xda,
	0xbb, 0x31, 0x13, 0xdc, 0x91, 0xee, 0x57, 0x9c, 0x30, 0xb4, 0x05, 0x8d, 0x82, 0x8b, 0x69, 0x52,
	0xfe, 0x05, 0xfe, 0xd1, 0xb7, 0x39, 0xde, 0xfc, 0xae, 0x40, 0xfb, 0x0a, 0xa3, 0x4f, 0xe8, 0x49,
	0x3c, 0x21, 0xe8, 0x00, 0xd0, 0x62, 0xe8, 0xd0, 0x93, 0x45, 0x6a, 0x61, 0xd8, 0x3b, 0xbd, 0xeb,
	0x01, 0x59, 0x9a, 0x09, 0x2d, 0x86, 0x4c, 0x24, 0x24, 0xcc, 0xae, 0x48, 0xa8, 0x22, 0xb3, 0x29,
	0xac, 0x09, 0x53, 0x82, 0x36, 0x16, 0x29, 0xaa, 0x32, 0xda, 0xd9, 0xbc, 0x36, 0xb6, 0x50, 0x14,
	0x06, 0x43, 0xa4, 0x58, 0x95, 0x3a, 0x91, 0x62, 0x75, 0xda, 0xa6, 0xb0, 0x2a, 0x48, 0x09, 0x43,
	0x02, 0x97, 0xc4, 0x39, 0xeb, 0x5c, 0x17, 0xc9, 0x9e, 0x4b, 0xdb, 0xe8, 0xd3, 0xf9, 0x43, 0x1e,
	0x16, 0xe0, 0xcf, 0xf5, 0xfc, 0x85, 0x7f, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xba, 0x4b, 0xed,
	0xa9, 0xf1, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RatelimitConfigServiceClient is the client API for RatelimitConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RatelimitConfigServiceClient interface {
	AddRatelimitConfig(ctx context.Context, in *AddRatelimitConfigReq, opts ...grpc.CallOption) (*AddRatelimitConfigResp, error)
	GetRatelimitConfig(ctx context.Context, in *GetRatelimitConfigReq, opts ...grpc.CallOption) (*GetRatelimitConfigResp, error)
	UpdateRatelimitConfig(ctx context.Context, in *UpdateRatelimitConfigReq, opts ...grpc.CallOption) (*UpdateRatelimitConfigResp, error)
	DeleteRatelimitConfig(ctx context.Context, in *DeleteRatelimitConfigReq, opts ...grpc.CallOption) (*DeleteRatelimitConfigResp, error)
	ListRatelimitConfigs(ctx context.Context, in *ListRatelimitConfigReq, opts ...grpc.CallOption) (RatelimitConfigService_ListRatelimitConfigsClient, error)
}

type ratelimitConfigServiceClient struct {
	cc *grpc.ClientConn
}

func NewRatelimitConfigServiceClient(cc *grpc.ClientConn) RatelimitConfigServiceClient {
	return &ratelimitConfigServiceClient{cc}
}

func (c *ratelimitConfigServiceClient) AddRatelimitConfig(ctx context.Context, in *AddRatelimitConfigReq, opts ...grpc.CallOption) (*AddRatelimitConfigResp, error) {
	out := new(AddRatelimitConfigResp)
	err := c.cc.Invoke(ctx, "/ratelimit.config.RatelimitConfigService/AddRatelimitConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratelimitConfigServiceClient) GetRatelimitConfig(ctx context.Context, in *GetRatelimitConfigReq, opts ...grpc.CallOption) (*GetRatelimitConfigResp, error) {
	out := new(GetRatelimitConfigResp)
	err := c.cc.Invoke(ctx, "/ratelimit.config.RatelimitConfigService/GetRatelimitConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratelimitConfigServiceClient) UpdateRatelimitConfig(ctx context.Context, in *UpdateRatelimitConfigReq, opts ...grpc.CallOption) (*UpdateRatelimitConfigResp, error) {
	out := new(UpdateRatelimitConfigResp)
	err := c.cc.Invoke(ctx, "/ratelimit.config.RatelimitConfigService/UpdateRatelimitConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratelimitConfigServiceClient) DeleteRatelimitConfig(ctx context.Context, in *DeleteRatelimitConfigReq, opts ...grpc.CallOption) (*DeleteRatelimitConfigResp, error) {
	out := new(DeleteRatelimitConfigResp)
	err := c.cc.Invoke(ctx, "/ratelimit.config.RatelimitConfigService/DeleteRatelimitConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratelimitConfigServiceClient) ListRatelimitConfigs(ctx context.Context, in *ListRatelimitConfigReq, opts ...grpc.CallOption) (RatelimitConfigService_ListRatelimitConfigsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RatelimitConfigService_serviceDesc.Streams[0], "/ratelimit.config.RatelimitConfigService/ListRatelimitConfigs", opts...)
	if err != nil {
		return nil, err
	}
	x := &ratelimitConfigServiceListRatelimitConfigsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RatelimitConfigService_ListRatelimitConfigsClient interface {
	Recv() (*ListRatelimitConfigRes, error)
	grpc.ClientStream
}

type ratelimitConfigServiceListRatelimitConfigsClient struct {
	grpc.ClientStream
}

func (x *ratelimitConfigServiceListRatelimitConfigsClient) Recv() (*ListRatelimitConfigRes, error) {
	m := new(ListRatelimitConfigRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RatelimitConfigServiceServer is the server API for RatelimitConfigService service.
type RatelimitConfigServiceServer interface {
	AddRatelimitConfig(context.Context, *AddRatelimitConfigReq) (*AddRatelimitConfigResp, error)
	GetRatelimitConfig(context.Context, *GetRatelimitConfigReq) (*GetRatelimitConfigResp, error)
	UpdateRatelimitConfig(context.Context, *UpdateRatelimitConfigReq) (*UpdateRatelimitConfigResp, error)
	DeleteRatelimitConfig(context.Context, *DeleteRatelimitConfigReq) (*DeleteRatelimitConfigResp, error)
	ListRatelimitConfigs(*ListRatelimitConfigReq, RatelimitConfigService_ListRatelimitConfigsServer) error
}

// UnimplementedRatelimitConfigServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRatelimitConfigServiceServer struct {
}

func (*UnimplementedRatelimitConfigServiceServer) AddRatelimitConfig(ctx context.Context, req *AddRatelimitConfigReq) (*AddRatelimitConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRatelimitConfig not implemented")
}
func (*UnimplementedRatelimitConfigServiceServer) GetRatelimitConfig(ctx context.Context, req *GetRatelimitConfigReq) (*GetRatelimitConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatelimitConfig not implemented")
}
func (*UnimplementedRatelimitConfigServiceServer) UpdateRatelimitConfig(ctx context.Context, req *UpdateRatelimitConfigReq) (*UpdateRatelimitConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRatelimitConfig not implemented")
}
func (*UnimplementedRatelimitConfigServiceServer) DeleteRatelimitConfig(ctx context.Context, req *DeleteRatelimitConfigReq) (*DeleteRatelimitConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRatelimitConfig not implemented")
}
func (*UnimplementedRatelimitConfigServiceServer) ListRatelimitConfigs(req *ListRatelimitConfigReq, srv RatelimitConfigService_ListRatelimitConfigsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListRatelimitConfigs not implemented")
}

func RegisterRatelimitConfigServiceServer(s *grpc.Server, srv RatelimitConfigServiceServer) {
	s.RegisterService(&_RatelimitConfigService_serviceDesc, srv)
}

func _RatelimitConfigService_AddRatelimitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRatelimitConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatelimitConfigServiceServer).AddRatelimitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ratelimit.config.RatelimitConfigService/AddRatelimitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatelimitConfigServiceServer).AddRatelimitConfig(ctx, req.(*AddRatelimitConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatelimitConfigService_GetRatelimitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatelimitConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatelimitConfigServiceServer).GetRatelimitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ratelimit.config.RatelimitConfigService/GetRatelimitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatelimitConfigServiceServer).GetRatelimitConfig(ctx, req.(*GetRatelimitConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatelimitConfigService_UpdateRatelimitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRatelimitConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatelimitConfigServiceServer).UpdateRatelimitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ratelimit.config.RatelimitConfigService/UpdateRatelimitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatelimitConfigServiceServer).UpdateRatelimitConfig(ctx, req.(*UpdateRatelimitConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatelimitConfigService_DeleteRatelimitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRatelimitConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatelimitConfigServiceServer).DeleteRatelimitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ratelimit.config.RatelimitConfigService/DeleteRatelimitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatelimitConfigServiceServer).DeleteRatelimitConfig(ctx, req.(*DeleteRatelimitConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatelimitConfigService_ListRatelimitConfigs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRatelimitConfigReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatelimitConfigServiceServer).ListRatelimitConfigs(m, &ratelimitConfigServiceListRatelimitConfigsServer{stream})
}

type RatelimitConfigService_ListRatelimitConfigsServer interface {
	Send(*ListRatelimitConfigRes) error
	grpc.ServerStream
}

type ratelimitConfigServiceListRatelimitConfigsServer struct {
	grpc.ServerStream
}

func (x *ratelimitConfigServiceListRatelimitConfigsServer) Send(m *ListRatelimitConfigRes) error {
	return x.ServerStream.SendMsg(m)
}

var _RatelimitConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ratelimit.config.RatelimitConfigService",
	HandlerType: (*RatelimitConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRatelimitConfig",
			Handler:    _RatelimitConfigService_AddRatelimitConfig_Handler,
		},
		{
			MethodName: "GetRatelimitConfig",
			Handler:    _RatelimitConfigService_GetRatelimitConfig_Handler,
		},
		{
			MethodName: "UpdateRatelimitConfig",
			Handler:    _RatelimitConfigService_UpdateRatelimitConfig_Handler,
		},
		{
			MethodName: "DeleteRatelimitConfig",
			Handler:    _RatelimitConfigService_DeleteRatelimitConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListRatelimitConfigs",
			Handler:       _RatelimitConfigService_ListRatelimitConfigs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "config.proto",
}
